# Generated by Django 3.1.3 on 2020-11-19 23:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_welcompage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelcomPage',
            new_name='WelcomePage',
        ),
    ]
