# Generated by Django 3.1.3 on 2020-11-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201119_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomepage',
            name='image',
        ),
    ]
