# Generated by Django 3.1.3 on 2020-11-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0007_remove_welcomepage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomePage',
        ),
    ]
